services:
  backend:
    image: docker.registry.home.adhityan.com/resto-ai-backend
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    network_mode: bridge
